environment: prod
namespace: catalogue-prod

services:
  - name: auth-service-prod
    pod: "auth-service-prod-.*"
  - name: user-service-prod
    pod: "user-service-prod-.*"
  - name: project-service-prod
    pod: "project-service-prod-.*"

