replicaCount: 1

image:
  repository: project-catalogue-project-service
  tag: latest
  pullPolicy: Never

containerPort: 8082

service:
  port: 8082

probes:
  path: /actuator/health

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

serviceAccount:
  create: true

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 15s

config:
  springProfile: dev
  userServiceUrl: http://user-service.catalogue-dev.svc.cluster.local:8081

secret:
  jwtSecret: bXktc3VwZXItc2VjcmV0LWtleS1mb3ItZGV2LWVudmlyb25tZW50LTEyMzQ1Njc4OQ==
  dbUrl: jdbc:postgresql://postgresql.database.svc.cluster.local:5432/dev_project_db
  dbUsername: postgres
  dbPassword: catalogue_postgres

