replicaCount: 2

image:
  repository: project-catalogue-project-service
  tag: latest
  pullPolicy: Never

containerPort: 8082

service:
  port: 8082

probes:
  path: /actuator/health

resources:
  requests:
    cpu: 150m
    memory: 384Mi
  limits:
    cpu: 750m
    memory: 768Mi

serviceAccount:
  create: true

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 15s

config:
  springProfile: prod
  userServiceUrl: http://user-service-prod.catalogue-prod.svc.cluster.local:8081

secret:
  jwtSecret: bXktand0U2VjcmV0LWZvci1wcm9kLWVudmlyb25tZW50LXBvcnR1Z2FsLWxpc2JvYS0yMDI2
  dbUrl: jdbc:postgresql://postgresql.database.svc.cluster.local:5432/prod_project_db
  dbUsername: postgres
  dbPassword: catalogue_postgres

