replicaCount: 1

image:
  repository: project-catalogue-project-service
  tag: latest
  pullPolicy: Never

containerPort: 8082

service:
  port: 8082

probes:
  path: /actuator/health

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  create: true

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 15s

config:
  springProfile: dev
  userServiceUrl: http://user-service-dev.catalogue-dev.svc.cluster.local:8081
  kafkaBootstrapServers: kafka.messaging.svc.cluster.local:9092
  userDeletedTopic: dev.user.deleted
  kafkaConsumerGroupId: project-service-dev

secret:
  jwtSecret: bXktand0U2VjcmV0LWZvci1kZXYtZW52aXJvbm1lbnQtcG9ydHVnYWwtbGlzYm9hLTIwMjY=
  dbUrl: jdbc:postgresql://postgresql.database.svc.cluster.local:5432/dev_project_db
  dbUsername: postgres
  dbPassword: catalogue_postgres

