apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc | quote }}

