replicaCount: 1

image:
  repository: project-catalogue-auth-service
  tag: latest
  pullPolicy: Never

containerPort: 8083

service:
  port: 8083

probes:
  path: /actuator/health

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  create: true

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 15s

config:
  springProfile: dev
  userServiceUrl: http://user-service-dev.catalogue-dev.svc.cluster.local:8081
  jwtExpirationMs: "120000"
  allowedClientIds: "client-user-01,client-admin-01"
  adminClientIds: "client-admin-01"

secret:
  jwtSecret: bXktand0U2VjcmV0LWZvci1kZXYtZW52aXJvbm1lbnQtcG9ydHVnYWwtbGlzYm9hLTIwMjY=

