apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project-service.fullname" . }}
  labels:
    {{- include "project-service.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc | quote }}
  DB_JDBC_URL: {{ .Values.secret.dbJdbcUrl | b64enc | quote }}
  DB_USERNAME: {{ .Values.secret.dbUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}

