apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project-service.fullname" . }}
  labels:
    {{- include "project-service.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.secret.dbUrl | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.dbUsername | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: {{ "org.postgresql.Driver" | b64enc | quote }}

