replicaCount: 2

image:
  repository: project-catalogue-user-service
  tag: latest
  pullPolicy: Never

containerPort: 8081

service:
  port: 8081

probes:
  path: /actuator/health

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  create: true

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 15s

config:
  springProfile: prod

secret:
  jwtSecret: ""
  dbJdbcUrl: jdbc:postgresql://postgresql.database.svc.cluster.local:5432/prod_user_db
  dbUsername: postgres
  dbPassword: catalogue_postgres

